version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    cap_add: 
      - SYS_NICE
    restart: always
    environment:
      POSTGRES_PASSWORD:  ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    ports:
      - '5034:5432'
    volumes:
      - db_data:/var/lib/postgresql


volumes:
  db_data:
    
