CodePipeline:
  Type: "AWS::CodePipeline::Pipeline"
  Properties:
    RoleArn: !GetAtt CodePipelineServiceRole.Arn
    Stages:
      - Name: Source
        Actions:
          - Name: Source
            ActionTypeId:
              Category: Source
              Owner: AWS
              Provider: CodeCommit
              Version: 1
            OutputArtifacts:
              - Name: SourceArtifact
            Configuration:
              RepositoryName: !Ref CodeCommitRepository
              BranchName: master
      - Name: Build
        Actions:
          - Name: Build
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: 1
            InputArtifacts:
              - Name: SourceArtifact
            OutputArtifacts:
              - Name: BuildArtifact
            Configuration:
              ProjectName: !Ref CodeBuildProject
      - Name: Deploy
        Actions:
          - Name: Deploy
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Provider: CloudFormation
              Version: 1
            InputArtifacts:
              - Name: BuildArtifact
            Configuration:
              StackName: !Sub "${AWS::StackName}-deploy"
              Capabilities: CAPABILITY_NAMED_IAM
              TemplatePath: BuildArtifact::output.yml

CodePipelineServiceRole:
  Type: "AWS::IAM::Role"
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: "codepipeline.amazonaws.com"
          Action: "sts:AssumeRole"
    Path: /
    Policies:
      - PolicyName: CodePipelinePolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "s3:*"
                - "codebuild:*"
                - "codedeploy:*"
                - "cloudformation:*"
                - "iam:*"
              Resource: "*"

CodeCommitRepository:
  Type: "AWS::CodeCommit::Repository"
  Properties:
    RepositoryName: !Sub "${AWS::StackName}-repo"
    RepositoryDescription: "E-commerce Flask application source code repository"

CodeBuildProject:
  Type: "AWS::CodeBuild::Project"
  Properties:
    Name: !Sub "${AWS::StackName}-build"
    Source:
      Type: CODEPIPELINE
    Artifacts:
      Type: CODEPIPELINE
    Environment:
      ComputeType: BUILD_GENERAL1_SMALL
      Image: "aws/codebuild/standard:5.0"
      Type: LINUX_CONTAINER
    ServiceRole: !GetAtt CodeBuildServiceRole.Arn

CodeBuildServiceRole:
  Type: "AWS::IAM::Role"
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: "codebuild.amazonaws.com"
          Action: "sts:AssumeRole"
    Path: /
    Policies:
      - PolicyName: CodeBuildPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "logs:*"
                - "s3:*"
                - "codepipeline:*"
                - "codebuild:*"
                - "cloudformation:*"
                - "iam:*"
              Resource: "*"
